sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1120

  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5t8WkPXF4pBUbqEg82yy
    access-key-secret: SqvwdIBhIsK3FmGclxzDMoBUN6AZ82
    bucket-name: sky-take-out-tk1120
  redis:
#    host: 192.168.8.128
    host: 127.0.0.1
    port: 6379
    password: 1120
    database: 10